# Generated by Django 4.0.5 on 2022-06-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messageMod',
            new_name='message',
        ),
    ]
